In [ ]:
import pandas as pd
items_path = 'items.csv'
transactions_path = 'transactions_2015.csv'
holidays_path = 'holidays_2015.csv'
stores_path = 'quito_stores.csv'
train_path = 'train_subset_2015.csv'
oil_path='oil_prices_filled.csv'

items = pd.read_csv(items_path, dtype={'item_nbr': 'int32', 'family': 'category', 'perishable': 'int8'})
transactions = pd.read_csv(transactions_path, dtype={'store_nbr': 'int16', 'transactions': 'int32'})
holidays = pd.read_csv(holidays_path, dtype={'type': 'category', 'transferred': 'bool'})
stores = pd.read_csv(stores_path, dtype={'store_nbr': 'int16', 'city': 'category', 'state': 'category', 'cluster': 'int8'})
weather=pd.read_csv('weather_2015_filled.csv')
oil=pd.read_csv(oil_path)
# Add a 'holiday' column to holidays DataFrame
holidays['holiday'] = 1  # Mark all rows as holidays

# Read the first 1,000,000 rows from train.csv
train = pd.read_csv(
    train_path,
    dtype={'id': 'int32', 'item_nbr': 'int32', 'store_nbr': 'int16', 'unit_sales': 'float32'},
    nrows=1000000,
)

<ipython-input-1-da54659b570c>:19: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv(

In [ ]:


# Load auxiliary files with memory-efficient data types

# Merge with holidays
train = pd.merge(train, holidays, on='date', how='left')
train['holiday'] = train['holiday'].fillna(0).astype(int)

# Merge with items
train = pd.merge(train, items, on='item_nbr', how='left')

# Merge with stores
train = pd.merge(train, stores, on='store_nbr', how='left')

# Merge with transactions
train = pd.merge(train, transactions, on=['store_nbr', 'date'], how='left')
train = pd.merge(train, weather, on='date', how='left')
train = pd.merge(train, oil, on='date', how='left')
# # Fill missing transaction values with 0
train['transactions'] = train['transactions'].fillna(0).astype(int)

# Save the merged DataFrame to a new CSV file
# train.to_csv("merged_data_1M.csv", index=False)

In [ ]:
pd.set_option('display.max_rows', None)

train.tail(1000)

              id        date  store_nbr  item_nbr  unit_sales onpromotion  \
936095  40829425  2015-02-08         49   1239808   10.000000       False
936096  40829426  2015-02-08         49   1239809   22.000000       False
936097  40829427  2015-02-08         49   1239810   20.000000       False
936098  40829428  2015-02-08         49   1239812    3.000000       False
936099  40829429  2015-02-08         49   1239813   11.000000       False
936100  40829430  2015-02-08         49   1239815    3.000000       False
936101  40829431  2015-02-08         49   1239817    8.000000       False
936102  40829432  2015-02-08         49   1239818   21.000000       False
936103  40829433  2015-02-08         49   1239819   17.000000       False
936104  40829434  2015-02-08         49   1239820    1.000000       False
936105  40829435  2015-02-08         49   1239844    9.000000       False
936106  40829436  2015-02-08         49   1239845   13.000000       False
936107  40829437  2015-02-08         49   1239846   15.000000       False
936108  40829438  2015-02-08         49   1239847    7.000000       False
936109  40829439  2015-02-08         49   1239852   18.577999       False
936110  40829440  2015-02-08         49   1239853   26.787001       False
936111  40829441  2015-02-08         49   1239854   28.246000       False
936112  40829442  2015-02-08         49   1239855   10.173000       False
936113  40829443  2015-02-08         49   1239856   32.391998       False
936114  40829444  2015-02-08         49   1239857   36.921001       False
936115  40829445  2015-02-08         49   1239858   22.027000       False
936116  40829446  2015-02-08         49   1239859   23.306000       False
936117  40829447  2015-02-08         49   1239860   28.917999       False
936118  40829448  2015-02-08         49   1239861   33.437000       False
936119  40829449  2015-02-08         49   1239862    9.105000       False
936120  40829450  2015-02-08         49   1239867   24.898001       False
936121  40829451  2015-02-08         49   1239868   43.907001       False
936122  40829452  2015-02-08         49   1239869    1.022000       False
936123  40829453  2015-02-08         49   1239875   15.452000       False
936124  40829454  2015-02-08         49   1239877   16.938999       False
936125  40829455  2015-02-08         49   1239880   15.536000       False
936126  40829456  2015-02-08         49   1239881   11.831000       False
936127  40829457  2015-02-08         49   1239883    6.454000       False
936128  40829458  2015-02-08         49   1239887    6.000000       False
936129  40829459  2015-02-08         49   1239890   26.416000       False
936130  40829460  2015-02-08         49   1239891   15.463000       False
936131  40829461  2015-02-08         49   1239897  124.833000       False
936132  40829462  2015-02-08         49   1239898    7.390000       False
936133  40829463  2015-02-08         49   1239899   30.208000       False
936134  40829464  2015-02-08         49   1239901   73.919998       False
936135  40829465  2015-02-08         49   1239902   78.139000       False
936136  40829466  2015-02-08         49   1239903   14.647000       False
936137  40829467  2015-02-08         49   1239905    1.000000       False
936138  40829468  2015-02-08         49   1239906   13.000000       False
936139  40829469  2015-02-08         49   1239908   12.000000       False
936140  40829470  2015-02-08         49   1239911   24.000000       False
936141  40829471  2015-02-08         49   1239912    4.000000       False
936142  40829472  2015-02-08         49   1239913    9.000000       False
936143  40829473  2015-02-08         49   1239914   13.000000       False
936144  40829474  2015-02-08         49   1239915    1.000000       False
936145  40829475  2015-02-08         49   1239918   11.000000       False
936146  40829476  2015-02-08         49   1239953    3.000000       False
936147  40829477  2015-02-08         49   1239955   17.000000       False
936148  40829478  2015-02-08         49   1239956   18.000000       False
936149  40829479  2015-02-08         49   1242666    6.000000       False
936150  40829480  2015-02-08         49   1242667    7.000000       False
936151  40829481  2015-02-08         49   1243803   14.000000       False
936152  40829482  2015-02-08         49   1243814    6.000000       False
936153  40829483  2015-02-08         49   1243816    3.000000       False
936154  40829484  2015-02-08         49   1245918    6.000000       False
936155  40829485  2015-02-08         49   1246495    2.000000       False
936156  40829486  2015-02-08         49   1246498    5.000000       False
936157  40829487  2015-02-08         49   1246757   17.000000       False
936158  40829488  2015-02-08         49   1246758   12.000000       False
936159  40829489  2015-02-08         49   1246784    6.000000       False
936160  40829490  2015-02-08         49   1247036    5.000000       False
936161  40829491  2015-02-08         49   1248391   11.000000       False
936162  40829492  2015-02-08         49   1248394    2.000000       False
936163  40829493  2015-02-08         49   1248464    5.000000       False
936164  40829494  2015-02-08         49   1250226    1.000000       False
936165  40829495  2015-02-08         49   1253765    6.000000       False
936166  40829496  2015-02-08         49   1254013   24.000000       False
936167  40829497  2015-02-08         49   1254310    5.000000       False
936168  40829498  2015-02-08         49   1255777   20.000000       False
936169  40829499  2015-02-08         49   1257555    4.000000       False
936170  40829500  2015-02-08         49   1259006   14.000000       False
936171  40829501  2015-02-08         49   1259007   24.000000       False
936172  40829502  2015-02-08         49   1260238    1.000000       False
936173  40829503  2015-02-08         49   1273024    6.000000       False
936174  40829504  2015-02-08         49   1279049   16.000000       False
936175  40829505  2015-02-08         49   1280677    5.000000       False
936176  40829506  2015-02-08         49   1281011    3.000000       False
936177  40829507  2015-02-08         49   1281253    2.000000       False
936178  40829508  2015-02-08         49   1281780    1.000000       False
936179  40829509  2015-02-08         49   1282207    6.000000       False
936180  40829510  2015-02-08         49   1284221   10.000000       False
936181  40829511  2015-02-08         49   1285150    2.000000       False
936182  40829512  2015-02-08         49   1285154   27.000000       False
936183  40829513  2015-02-08         49   1288226    4.789000       False
936184  40829514  2015-02-08         49   1289417    5.000000       False
936185  40829515  2015-02-08         49   1289418    6.000000       False
936186  40829516  2015-02-08         49   1299616    8.000000       False
936187  40829517  2015-02-08         49   1302670    3.000000       False
936188  40829518  2015-02-08         49   1303141   16.000000       False
936189  40829519  2015-02-08         49   1304243   11.000000       False
936190  40829520  2015-02-08         49   1304491    1.000000       False
936191  40829521  2015-02-08         49   1305845   30.000000       False
936192  40829522  2015-02-08         49   1306155    2.000000       False
936193  40829523  2015-02-08         49   1306196    2.000000       False
936194  40829524  2015-02-08         49   1306197    8.000000       False
936195  40829525  2015-02-08         49   1306198   16.000000       False
936196  40829526  2015-02-08         49   1306199    4.000000       False
936197  40829527  2015-02-08         49   1309245    6.000000       False
936198  40829528  2015-02-08         49   1309246   54.000000       False
936199  40829529  2015-02-08         49   1309297  174.000000       False
936200  40829530  2015-02-08         49   1309298    7.000000       False
936201  40829531  2015-02-08         49   1309560   11.000000       False
936202  40829532  2015-02-08         49   1309672    5.000000       False
936203  40829533  2015-02-08         49   1309856    5.000000       False
936204  40829534  2015-02-08         49   1310076    7.000000       False
936205  40829535  2015-02-08         49   1312957    5.000000       False
936206  40829536  2015-02-08         49   1313222   21.000000       False
936207  40829537  2015-02-08         49   1313223   27.000000       False
936208  40829538  2015-02-08         49   1314409   15.000000       False
936209  40829539  2015-02-08         49   1316369    6.000000       False
936210  40829540  2015-02-08         49   1317094   12.000000       False
936211  40829541  2015-02-08         49   1317095    8.000000       False
936212  40829542  2015-02-08         49   1317096    7.000000       False
936213  40829543  2015-02-08         49   1320180    7.000000       False
936214  40829544  2015-02-08         49   1320701   19.000000       False
936215  40829545  2015-02-08         49   1321336    3.000000       False
936216  40829546  2015-02-08         49   1321497   10.000000       False
936217  40829547  2015-02-08         49   1322479   33.000000       False
936218  40829548  2015-02-08         49   1323422    2.000000       False
936219  40829549  2015-02-08         49   1324174    8.000000       False
936220  40829550  2015-02-08         49   1324182    1.000000       False
936221  40829551  2015-02-08         49   1324591    9.000000       False
936222  40829552  2015-02-08         49   1324667   14.000000       False
936223  40829553  2015-02-08         49   1324668   17.000000       False
936224  40829554  2015-02-08         49   1324670    4.000000       False
936225  40829555  2015-02-08         49   1324845    4.000000       False
936226  40829556  2015-02-08         49   1328340   10.000000       False
936227  40829557  2015-02-08         49   1328471    2.000000       False
936228  40829558  2015-02-08         49   1328495   19.000000       False
936229  40829559  2015-02-08         49   1328907   48.000000       False
936230  40829560  2015-02-08         49   1331407   10.000000       False
936231  40829561  2015-02-08         49   1332103   17.000000       False
936232  40829562  2015-02-08         49   1332664    6.000000       False
936233  40829563  2015-02-08         49   1333224    3.000000       False
936234  40829564  2015-02-08         49   1333307  183.000000       False
936235  40829565  2015-02-08         49   1333994   21.000000       False
936236  40829566  2015-02-08         49   1336459    7.000000       False
936237  40829567  2015-02-08         49   1336461    5.000000       False
936238  40829568  2015-02-08         49   1339795    3.000000       False
936239  40829569  2015-02-08         49   1342003   11.000000       False
936240  40829570  2015-02-08         49   1342006   15.000000       False
936241  40829571  2015-02-08         49   1342007    3.000000       False
936242  40829572  2015-02-08         49   1342008    5.000000       False
936243  40829573  2015-02-08         49   1342009    7.000000       False
936244  40829574  2015-02-08         49   1344514    3.000000       False
936245  40829575  2015-02-08         49   1345067    3.000000       False
936246  40829576  2015-02-08         49   1345068    1.000000       False
936247  40829577  2015-02-08         49   1345070    4.000000       False
936248  40829578  2015-02-08         49   1345071    1.000000       False
936249  40829579  2015-02-08         49   1345337    7.000000       False
936250  40829580  2015-02-08         49   1345352   12.000000       False
936251  40829581  2015-02-08         49   1345981    4.000000       False
936252  40829582  2015-02-08         49   1346410   10.000000        True
936253  40829583  2015-02-08         49   1346624    8.000000       False
936254  40829584  2015-02-08         49   1346625    5.000000       False
936255  40829585  2015-02-08         49   1346626   11.000000        True
936256  40829586  2015-02-08         49   1346627   12.000000       False
936257  40829587  2015-02-08         49   1346628   15.000000       False
936258  40829588  2015-02-08         49   1346629    7.000000       False
936259  40829589  2015-02-08         49   1346630   12.000000       False
936260  40829590  2015-02-08         49   1346631    7.000000       False
936261  40829591  2015-02-08         49   1346632    9.000000       False
936262  40829592  2015-02-08         49   1346636   15.000000       False
936263  40829593  2015-02-08         49   1346638   18.000000       False
936264  40829594  2015-02-08         49   1346643    3.000000       False
936265  40829595  2015-02-08         49   1347811    1.000000       False
936266  40829596  2015-02-08         49   1347977    3.000000       False
936267  40829597  2015-02-08         49   1348983    6.000000       False
936268  40829598  2015-02-08         49   1349806    6.000000       False
936269  40829599  2015-02-08         49   1349807    5.000000       False
936270  40829600  2015-02-08         49   1349808    8.000000       False
936271  40829601  2015-02-08         49   1351305    9.000000       False
936272  40829602  2015-02-08         49   1352751    1.000000       False
936273  40829603  2015-02-08         49   1352754    1.000000       False
936274  40829604  2015-02-08         49   1353189   28.000000       False
936275  40829605  2015-02-08         49   1353191   13.000000       False
936276  40829606  2015-02-08         49   1354380    5.000000       False
936277  40829607  2015-02-08         49   1354381    4.000000       False
936278  40829608  2015-02-08         49   1354382    7.000000       False
936279  40829609  2015-02-08         49   1354383    9.000000       False
936280  40829610  2015-02-08         49   1354384    6.000000       False
936281  40829611  2015-02-08         49   1354385    5.000000       False
936282  40829612  2015-02-08         49   1354386    3.000000       False
936283  40829613  2015-02-08         49   1354388    7.000000       False
936284  40829614  2015-02-08         49   1354389    3.000000       False
936285  40829615  2015-02-08         49   1354390    7.000000       False
936286  40829616  2015-02-08         49   1354711  100.000000       False
936287  40829617  2015-02-08         49   1354712   19.000000       False
936288  40829618  2015-02-08         49   1354713   30.000000       False
936289  40829619  2015-02-08         49   1354714   58.000000       False
936290  40829620  2015-02-08         49   1359503    1.000000       False
936291  40829621  2015-02-08         49   1360009    4.000000       False
936292  40829622  2015-02-08         49   1361205    9.000000       False
936293  40829623  2015-02-08         49   1363876   10.000000       False
936294  40829624  2015-02-08         49   1364636    2.000000       False
936295  40829625  2015-02-08         49   1366213   12.000000       False
936296  40829626  2015-02-08         49   1367273    1.000000       False
936297  40829627  2015-02-08         49   1367438    2.000000       False
936298  40829628  2015-02-08         49   1369793    1.000000       False
936299  40829629  2015-02-08         49   1369873    1.000000       False
936300  40829630  2015-02-08         49   1369973    2.000000       False
936301  40829631  2015-02-08         49   1370564   35.000000       False
936302  40829632  2015-02-08         49   1370568    2.000000       False
936303  40829633  2015-02-08         49   1371618   28.000000       False
936304  40829634  2015-02-08         49   1371620    3.000000       False
936305  40829635  2015-02-08         49   1372308    1.000000       False
936306  40829636  2015-02-08         49   1372309    1.000000       False
936307  40829637  2015-02-08         49   1372563    3.000000       False
936308  40829638  2015-02-08         49   1372862    1.000000       False
936309  40829639  2015-02-08         49   1373408   22.000000       False
936310  40829640  2015-02-08         49   1373444    1.000000       False
936311  40829641  2015-02-08         49   1386220    2.000000       False
936312  40829642  2015-02-08         49   1386250    2.000000       False
936313  40829643  2015-02-08         49   1386506    1.000000       False
936314  40829644  2015-02-08         49   1386696    2.000000       False
936315  40829645  2015-02-08         49   1388559    3.000000       False
936316  40829646  2015-02-08         49   1392260    1.000000       False
936317  40829647  2015-02-08         49   1392627    2.000000       False
936318  40829648  2015-02-08         49   1392628    5.000000       False
936319  40829649  2015-02-08         49   1393033    3.000000       False
936320  40829650  2015-02-08         49   1393047   14.000000       False
936321  40829651  2015-02-08         49   1394349    2.000000       False
936322  40829652  2015-02-08         49   1395693    3.000000       False
936323  40829653  2015-02-08         49   1396282    2.000000       False
936324  40829654  2015-02-08         49   1397060   15.000000       False
936325  40829655  2015-02-08         49   1397061   11.000000       False
936326  40829656  2015-02-08         49   1397062    5.000000       False
936327  40829657  2015-02-08         49   1397067    1.000000       False
936328  40829658  2015-02-08         49   1397797   12.000000       False
936329  40829659  2015-02-08         49   1397802    3.000000       False
936330  40829660  2015-02-08         49   1400328    3.000000       False
936331  40829661  2015-02-08         49   1400329    2.000000       False
936332  40829662  2015-02-08         49   1400330    3.000000       False
936333  40829663  2015-02-08         49   1400331    8.000000       False
936334  40829664  2015-02-08         49   1400332    4.000000       False
936335  40829665  2015-02-08         49   1400334    4.000000       False
936336  40829666  2015-02-08         49   1402545    2.000000       False
936337  40829667  2015-02-08         49   1402643   26.000000       False
936338  40829668  2015-02-08         49   1405685    8.000000       False
936339  40829669  2015-02-08         49   1411065    4.000000       False
936340  40829670  2015-02-08         49   1412575   12.281000       False
936341  40835085  2015-02-09          1    103520    6.000000       False
936342  40835086  2015-02-09          1    103665    1.000000       False
936343  40835087  2015-02-09          1    105574    8.000000       False
936344  40835088  2015-02-09          1    105575   12.000000       False
936345  40835089  2015-02-09          1    106716    2.000000       False
936346  40835090  2015-02-09          1    108634    2.000000       False
936347  40835091  2015-02-09          1    108698    4.000000       False
936348  40835092  2015-02-09          1    108701    1.000000       False
936349  40835093  2015-02-09          1    108786    3.000000       False
936350  40835094  2015-02-09          1    108797    4.000000       False
936351  40835095  2015-02-09          1    108862    1.000000       False
936352  40835096  2015-02-09          1    108952    7.000000       False
936353  40835097  2015-02-09          1    111223    2.000000       False
936354  40835098  2015-02-09          1    112830    1.000000       False
936355  40835099  2015-02-09          1    114778    2.000000       False
936356  40835100  2015-02-09          1    114790    8.000000       False
936357  40835101  2015-02-09          1    114799    1.000000       False
936358  40835102  2015-02-09          1    114800    2.000000       False
936359  40835103  2015-02-09          1    115267    3.000000       False
936360  40835104  2015-02-09          1    115611   10.000000        True
936361  40835105  2015-02-09          1    115693    4.000000       False
936362  40835106  2015-02-09          1    115720    4.000000       False
936363  40835107  2015-02-09          1    115850   13.000000       False

In [ ]:
train.drop(columns=['type_x', 'locale','locale_name','description','transferred','state','type_y','cluster',], inplace=True)
train.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,holiday,family,class,perishable,city,transactions,Avg Temperature (C),Min Temperature (C),Max Temperature (C),Precipitation (mm),year,month,dcoilwtico
0,38595440,2015-01-02,1,103665,6.0,False,1,BREAD/BAKERY,2712,1,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
1,38595441,2015-01-02,1,105575,3.0,False,1,GROCERY I,1045,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
2,38595442,2015-01-02,1,105577,1.0,False,1,GROCERY I,1045,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
3,38595443,2015-01-02,1,105693,1.0,False,1,GROCERY I,1034,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
4,38595444,2015-01-02,1,105857,2.0,False,1,GROCERY I,1092,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [ ]:
data = train.copy()
data.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,holiday,family,class,perishable,city,transactions,Avg Temperature (C),Min Temperature (C),Max Temperature (C),Precipitation (mm),year,month,dcoilwtico
0,38595440,2015-01-02,1,103665,6.0,False,1,BREAD/BAKERY,2712,1,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
1,38595441,2015-01-02,1,105575,3.0,False,1,GROCERY I,1045,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
2,38595442,2015-01-02,1,105577,1.0,False,1,GROCERY I,1045,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
3,38595443,2015-01-02,1,105693,1.0,False,1,GROCERY I,1034,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72
4,38595444,2015-01-02,1,105857,2.0,False,1,GROCERY I,1092,0,Quito,1021,13.8,7.0,20.4,4.7,2015,1,52.72

In [ ]:
# Gives a count of NaNs for each column
data['dcoilwtico'] = data['dcoilwtico'].fillna(data['dcoilwtico'].mean())
print(data.isna().sum())

id                     0
date                   0
store_nbr              0
item_nbr               0
unit_sales             0
onpromotion            1
holiday                0
family                 0
class                  0
perishable             0
city                   0
transactions           0
Avg Temperature (C)    0
Min Temperature (C)    0
Max Temperature (C)    0
Precipitation (mm)     0
year                   0
month                  0
dcoilwtico             0
dtype: int64

In [ ]:
data['date'] = pd.to_datetime(data['date'], format='%Y-%m-%d')
# Extract day of week and week of year
data['day_of_week'] = data['date'].dt.dayofweek
data['week_of_year'] = data['date'].dt.isocalendar().week

# Encode categorical variables
label_encoders = {}
for col in ['family', 'city']:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

# Scale numeric features
scaler = MinMaxScaler()
numeric_cols = ['unit_sales', 'transactions', 'Avg Temperature (C)', 'Min Temperature (C)',
                'Max Temperature (C)', 'Precipitation (mm)', 'perishable', 'day_of_week', 'week_of_year','dcoilwtico']
data[numeric_cols] = scaler.fit_transform(data[numeric_cols])

In [ ]:
pd.set_option('display.max_columns', None)
data.head()

,id,date,store_nbr,item_nbr,unit_sales,onpromotion,holiday,family,class,perishable,city,transactions,Avg Temperature (C),Min Temperature (C),Max Temperature (C),Precipitation (mm),year,month,dcoilwtico,day_of_week,week_of_year
0,38595440,2015-01-02,1,103665,0.044737,False,1,3,2712,1.0,0,0.108485,0.607843,0.692308,0.692308,0.261111,2015,1,0.964286,0.666667,0.0
1,38595441,2015-01-02,1,105575,0.043609,False,1,9,1045,0.0,0,0.108485,0.607843,0.692308,0.692308,0.261111,2015,1,0.964286,0.666667,0.0
2,38595442,2015-01-02,1,105577,0.042857,False,1,9,1045,0.0,0,0.108485,0.607843,0.692308,0.692308,0.261111,2015,1,0.964286,0.666667,0.0
3,38595443,2015-01-02,1,105693,0.042857,False,1,9,1034,0.0,0,0.108485,0.607843,0.692308,0.692308,0.261111,2015,1,0.964286,0.666667,0.0
4,38595444,2015-01-02,1,105857,0.043233,False,1,9,1092,0.0,0,0.108485,0.607843,0.692308,0.692308,0.261111,2015,1,0.964286,0.666667,0.0

In [ ]:
# Define the sequence length
seq_length = 14  # Weekly patterns

# Group data by store and item to create sequences
def create_sequences(data, seq_length):
    X, y = [], []
    grouped_data = data.groupby(['store_nbr', 'item_nbr'])
    for _, group in grouped_data:
        group = group.sort_values(by='date')  # Ensure chronological order
        group = group.reset_index(drop=True)
        values = group[['unit_sales', 'transactions', 'Avg Temperature (C)',
                        'Min Temperature (C)', 'Max Temperature (C)', 'Precipitation (mm)',
                        'perishable','day_of_week', 'week_of_year','dcoilwtico']].values
        for i in range(len(values) - seq_length):
            X.append(values[i:i + seq_length])  # Input sequence
            y.append(values[i + seq_length, 0])  # Target: unit_sales
    return np.array(X), np.array(y)

X, y = create_sequences(data, seq_length)
print(f"Shape of X: {X.shape}")  # (samples, seq_length, features)
print(f"Shape of y: {y.shape}")  # (samples,)

Shape of X: (521160, 14, 10)
Shape of y: (521160,)

In [ ]:
print(X[0][0])

[0.04473684 0.10848485 0.60784314 0.69230769 0.69230769 0.26111111
 1.         0.66666667 0.         0.96428571]

In [ ]:
# Use 80% of data for training and 20% for testing
split_index = int(0.8 * len(X))
X_train, X_test = X[:split_index], X[split_index:]
y_train, y_test = y[:split_index], y[split_index:]

print(f"Training samples: {len(X_train)}, Testing samples: {len(X_test)}")

Training samples: 416928, Testing samples: 104232

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Define the LSTM model
model = Sequential([
    LSTM(64, activation='relu', input_shape=(seq_length, X_train.shape[2]), return_sequences=True),
    Dropout(0.2),
    LSTM(64, activation='relu'),
    Dropout(0.2),
    Dense(1)  # Output layer: predict unit_sales
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=32,
    verbose=1
)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 264s 20ms/step - loss: 1.0608e-04 - mae: 0.0044 - val_loss: 2.8747e-05 - val_mae: 0.0029
Epoch 2/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 252s 19ms/step - loss: 5.1998e-05 - mae: 0.0026 - val_loss: 1.6735e-05 - val_mae: 0.0024
Epoch 3/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 267s 20ms/step - loss: 1.6969e-05 - mae: 0.0022 - val_loss: 2.1111e-05 - val_mae: 0.0026
Epoch 4/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 254s 19ms/step - loss: 1.5107e-05 - mae: 0.0021 - val_loss: 1.8215e-05 - val_mae: 0.0023
Epoch 5/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 259s 19ms/step - loss: 1.4151e-05 - mae: 0.0020 - val_loss: 1.5712e-05 - val_mae: 0.0021
Epoch 6/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 250s 19ms/step - loss: 1.3830e-05 - mae: 0.0019 - val_loss: 1.5719e-05 - val_mae: 0.0020
Epoch 7/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 281s 21ms/step - loss: 1.5024e-05 - mae: 0.0019 - val_loss: 1.3131e-05 - val_mae: 0.0019
Epoch 8/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 303s 19ms/step - loss: 1.2713e-05 - mae: 0.0019 - val_loss: 1.2886e-05 - val_mae: 0.0020
Epoch 9/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 288s 21ms/step - loss: 1.2521e-05 - mae: 0.0019 - val_loss: 1.5280e-05 - val_mae: 0.0021
Epoch 10/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 274s 21ms/step - loss: 1.2217e-05 - mae: 0.0019 - val_loss: 1.3538e-05 - val_mae: 0.0021
Epoch 11/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 311s 20ms/step - loss: 1.1348e-05 - mae: 0.0018 - val_loss: 1.7472e-05 - val_mae: 0.0024
Epoch 12/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 315s 20ms/step - loss: 1.1746e-05 - mae: 0.0018 - val_loss: 1.3476e-05 - val_mae: 0.0022
Epoch 13/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 266s 20ms/step - loss: 1.6211e-05 - mae: 0.0018 - val_loss: 1.3595e-05 - val_mae: 0.0019
Epoch 14/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 260s 20ms/step - loss: 1.2905e-05 - mae: 0.0018 - val_loss: 1.2661e-05 - val_mae: 0.0019
Epoch 15/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 253s 19ms/step - loss: 1.2634e-05 - mae: 0.0018 - val_loss: 1.2894e-05 - val_mae: 0.0019
Epoch 16/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 262s 19ms/step - loss: 1.0986e-05 - mae: 0.0018 - val_loss: 1.3508e-05 - val_mae: 0.0021
Epoch 17/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 264s 19ms/step - loss: 1.2735e-05 - mae: 0.0018 - val_loss: 1.4641e-05 - val_mae: 0.0022
Epoch 18/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 257s 19ms/step - loss: 1.1157e-05 - mae: 0.0018 - val_loss: 1.4955e-05 - val_mae: 0.0025
Epoch 19/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 263s 19ms/step - loss: 1.1833e-05 - mae: 0.0018 - val_loss: 1.4115e-05 - val_mae: 0.0024
Epoch 20/20
13029/13029 ━━━━━━━━━━━━━━━━━━━━ 262s 19ms/step - loss: 1.4449e-05 - mae: 0.0018 - val_loss: 1.3939e-05 - val_mae: 0.0023

In [ ]:
# Evaluate the model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss (MSE): {test_loss}, Test MAE: {test_mae}")

3258/3258 ━━━━━━━━━━━━━━━━━━━━ 26s 8ms/step - loss: 1.4052e-05 - mae: 0.0023
Test Loss (MSE): 1.3938707525085192e-05, Test MAE: 0.0022558337077498436

In [ ]:
y_pred = model.predict(X_test)
from sklearn.metrics import mean_absolute_percentage_error

mape = mean_absolute_percentage_error(y_test, y_pred)
accuracy = 100 - mape * 100  # Accuracy as a percentage
print(f"MAPE: {mape:.4f}, Accuracy: {accuracy:.2f}%")

3258/3258 ━━━━━━━━━━━━━━━━━━━━ 22s 7ms/step
MAPE: 0.0446, Accuracy: 95.54%

In [ ]:
# Prepare input for a specific store and product
store_nbr = 1
item_nbr = 103665

recent_data = data[(data['store_nbr'] == store_nbr) & (data['item_nbr'] == item_nbr)]
recent_data = recent_data.sort_values(by='date').tail(seq_length)

# Drop non-numeric columns and prepare for LSTM
recent_sequence = recent_data[['unit_sales', 'transactions', 'Avg Temperature (C)',
                               'Min Temperature (C)', 'Max Temperature (C)',
                               'Precipitation (mm)', 'perishable',
                               'day_of_week', 'week_of_year','dcoilwtico']].values.reshape(1, seq_length, -1)

# Predict next week's sales
next_week_prediction = model.predict(recent_sequence)
print(f"Predicted Sales for Next Week: {next_week_prediction[0][0]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Predicted Sales for Next Week: 0.04560328274965286